name: Python package

on: [push,  pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd ./python
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          cd ./python
          flake8 ./
      - name: Lint with MyPy
        run: |
          cd ./python
          mypy ./
      - name: Test with unittest
        run: |
          cd ./python
          python -m unittest
